// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WanderKiwi.Infrastructure.Data;

#nullable disable

namespace WanderKiwi.Infrastructure.Migrations
{
    [DbContext(typeof(WanderKiwiDbContext))]
    [Migration("20260823115312_AddTeAnauAttractions")]
    partial class AddTeAnauAttractions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailabilityNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BestTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHoursNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecommendedDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailabilityNote = "Open year round; alpine weather can affect gondola operations.",
                            BestTime = "Year round",
                            BookingNote = "Pre-book gondola and activities in peak periods; weather may affect operations.",
                            Description = "Take in breathtaking views of Queenstown, Lake Wakatipu and the surrounding mountains.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/skyline-queenstown.jpg",
                            Latitude = -45.028700000000001,
                            Longitude = 168.6558,
                            Name = "Skyline Queenstown",
                            OpeningHoursNote = "Check Skyline’s current operating hours before visit.",
                            Rating = 4.7m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 3447,
                            SourceUrl = "https://www.skyline.co.nz/en/queenstown/"
                        },
                        new
                        {
                            Id = 2,
                            AvailabilityNote = "Seasonal timetable; services can be affected by lake and weather conditions.",
                            BestTime = "Nov - Mar",
                            BookingNote = "Advance booking recommended; arrive at the wharf early and check weather cancellations.",
                            Description = "Enjoy a classic cruise across Lake Wakatipu aboard a historic steamship.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/tss-earnslaw-cruise.jpg",
                            Latitude = -45.032600000000002,
                            Longitude = 168.6575,
                            Name = "TSS Earnslaw Cruise",
                            OpeningHoursNote = "Check RealNZ’s current sailing timetable before visit.",
                            Rating = 4.4m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 80,
                            SourceUrl = "https://www.realnz.com/en/experiences/cruises/tss-earnslawe/"
                        },
                        new
                        {
                            Id = 3,
                            AvailabilityNote = "Operates year round, subject to river and weather conditions.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended; trips can be delayed or cancelled for weather or river conditions.",
                            Description = "High-speed jet boat ride through the Shotover River canyons.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/shotover-jet.jpg",
                            Latitude = -44.982900000000001,
                            Longitude = 168.67019999999999,
                            Name = "Shotover Jet",
                            OpeningHoursNote = "Check Shotover Jet’s current departure times before visit.",
                            Rating = 4.3m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 269,
                            SourceUrl = "https://www.shotoverjet.com/"
                        },
                        new
                        {
                            Id = 4,
                            AvailabilityNote = "Year round; check current seasonal operating times.",
                            BestTime = "Year round",
                            BookingNote = "Book online or check the official site before visiting; wildlife encounters and conservation shows run daily.",
                            Description = "Native wildlife conservation park near town centre.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/kiwi-park-queenstown.jpg",
                            Latitude = -45.029600000000002,
                            Longitude = 168.6557,
                            Name = "Kiwi Park Queenstown",
                            OpeningHoursNote = "Daily. The official site lists 9:30am–6:30pm with last entry 5:45pm, and a shorter 9:30am–5pm schedule with last entry 4:15pm; confirm the applicable season.",
                            Rating = 4.6m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 355,
                            SourceUrl = "https://kiwibird.co.nz/"
                        },
                        new
                        {
                            Id = 5,
                            AvailabilityNote = "Open year round; autumn colour is a seasonal highlight.",
                            BestTime = "Sep - Apr",
                            BookingNote = "No booking normally required; use daylight hours and allow for weather.",
                            Description = "Lakeside gardens and an easy walking loop near central Queenstown.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/queenstown-gardens.jpg",
                            Latitude = -45.0336,
                            Longitude = 168.66309999999999,
                            Name = "Queenstown Gardens",
                            OpeningHoursNote = "Public gardens; check Queenstown Lakes District Council information for facility updates.",
                            Rating = 4.4m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 1024,
                            SourceUrl = "https://www.queenstownnz.co.nz/listing/queenstown-gardens/120/"
                        },
                        new
                        {
                            Id = 6,
                            AvailabilityNote = "Open year round; autumn is especially popular.",
                            BestTime = "Year round",
                            BookingNote = "No booking for the precinct; allow extra time for parking during autumn and events.",
                            Description = "Historic gold-mining village with heritage streets and riverside walks.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/arrowtown-historic-precinct.jpg",
                            Latitude = -44.9392,
                            Longitude = 168.8313,
                            Name = "Arrowtown Historic Precinct",
                            OpeningHoursNote = "Public streets are accessible daily; check individual shops and museums for their hours.",
                            Rating = 4.3m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 864,
                            SourceUrl = "https://www.arrowtown.com/"
                        },
                        new
                        {
                            Id = 7,
                            AvailabilityNote = "Open year round; vineyard and cellar-door experiences vary seasonally.",
                            BestTime = "Year round",
                            BookingNote = "Book tastings, tours and dining in advance; appoint a sober driver or use a tour.",
                            Description = "Explore the region's oldest vineyards and New Zealand's largest wine cave.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/gibbston-valley-winery.jpg",
                            Latitude = -45.011600000000001,
                            Longitude = 168.86869999999999,
                            Name = "Gibbston Valley Winery",
                            OpeningHoursNote = "Check Gibbston Valley’s current cellar-door and restaurant hours before visit.",
                            Rating = 4.3m,
                            RecommendedDuration = "4 hours",
                            ReviewCount = 861,
                            SourceUrl = "https://www.gibbstonvalley.com/"
                        },
                        new
                        {
                            Id = 8,
                            AvailabilityNote = "Open year round; popular in winter and evenings.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking is essential; outdoor sessions may be weather affected.",
                            Description = "Private hot pools overlooking the Shotover River canyon.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/onsen-hot-pools.jpg",
                            Latitude = -44.984000000000002,
                            Longitude = 168.6687,
                            Name = "Onsen Hot Pools",
                            OpeningHoursNote = "Check Onsen Hot Pools’ current session times before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 17,
                            SourceUrl = "https://www.onsen.co.nz/"
                        },
                        new
                        {
                            Id = 9,
                            AvailabilityNote = "Open year round, subject to wind and weather limits.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended; weather can delay or cancel jumps.",
                            Description = "The world's first commercial bungy jump site, located at the historic Kawarau Bridge.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/kawarau-bungy-centre.jpg",
                            Latitude = -45.013399999999997,
                            Longitude = 168.89060000000001,
                            Name = "Kawarau Bungy Centre",
                            OpeningHoursNote = "Check AJ Hackett’s current operating hours before visit.",
                            Rating = 4.4m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 141,
                            SourceUrl = "https://www.bungy.co.nz/queenstown/kawarau-bungy-centre/"
                        },
                        new
                        {
                            Id = 10,
                            AvailabilityNote = "Skiing is seasonal; sightseeing and summer operations vary.",
                            BestTime = "Year round",
                            BookingNote = "Book rentals or lessons in advance; alpine road and lift access are weather dependent.",
                            Description = "A premier ski resort offering spectacular winter sports and summer sightseeing.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/coronet-peak.jpg",
                            Latitude = -44.928699999999999,
                            Longitude = 168.73599999999999,
                            Name = "Coronet Peak",
                            OpeningHoursNote = "Check NZSki’s current lift, road and operating status before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "5 hours",
                            ReviewCount = 2400,
                            SourceUrl = "https://www.coronetpeak.co.nz/"
                        },
                        new
                        {
                            Id = 11,
                            AvailabilityNote = "Best in dry conditions; snow, ice and strong wind can affect winter access.",
                            BestTime = "Year round",
                            BookingNote = "No booking; take water, layers and suitable footwear.",
                            Description = "A rewarding hike through pine forest to panoramic views of the Wakatipu basin.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/queenstown-hill-time-walk.jpg",
                            Latitude = -45.029499999999999,
                            Longitude = 168.6661,
                            Name = "Queenstown Hill Time Walk",
                            OpeningHoursNote = "Public walking track; start in daylight and check DOC/Queenstown weather advice.",
                            Rating = 4.8m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 36,
                            SourceUrl = "https://www.queenstownnz.co.nz/listing/queenstown-hill-time-walk/146/"
                        },
                        new
                        {
                            Id = 12,
                            AvailabilityNote = "Open year round; winter snow/ice and storm conditions may affect roads.",
                            BestTime = "Year round",
                            BookingNote = "No booking; fuel up, allow extra driving time, and do not rely on the route during road closures.",
                            Description = "A stunning coastal road trip tracing the edge of Lake Wakatipu to the gateway of Mount Aspiring National Park.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/glenorchy-scenic-drive.jpg",
                            Latitude = -44.846800000000002,
                            Longitude = 168.38460000000001,
                            Name = "Glenorchy Scenic Drive",
                            OpeningHoursNote = "Public road; check NZTA and weather conditions before departure.",
                            Rating = 4.6m,
                            RecommendedDuration = "6 hours",
                            ReviewCount = 1187,
                            SourceUrl = "https://www.queenstownnz.co.nz/things-to-do/scenic-drives/glenorchy-road/"
                        },
                        new
                        {
                            Id = 13,
                            AvailabilityNote = "Year round; road, avalanche and severe-weather disruptions are possible.",
                            BestTime = "Nov - Mar",
                            BookingNote = "Advance booking strongly recommended; carry food/water and expect weather-related changes.",
                            Description = "A spectacular fiord surrounded by towering peaks, waterfalls and native rainforest.",
                            DestinationId = 8,
                            ImageUrl = "assets/images/milford-sound-day-trip.jpg",
                            Latitude = -44.671500000000002,
                            Longitude = 167.9255,
                            Name = "Milford Sound day trip",
                            OpeningHoursNote = "Check operator timetable and NZTA road conditions before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "10 hours",
                            ReviewCount = 415,
                            SourceUrl = "https://www.realnz.com/en/experiences/cruises/milford-sound-cruises/"
                        },
                        new
                        {
                            Id = 14,
                            AvailabilityNote = "Open year round; best enjoyed in settled weather and daylight.",
                            BestTime = "Year round",
                            BookingNote = "No booking; check weather and water-safety advice before lake activities.",
                            Description = "A vibrant promenade perfect for a scenic stroll, lakeside dining, or watching the sunset.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/lake-wakatipu-waterfront.jpg",
                            Latitude = -45.033200000000001,
                            Longitude = 168.65989999999999,
                            Name = "Lake Wakatipu waterfront",
                            OpeningHoursNote = "Public waterfront; no set hours.",
                            Rating = 4.6m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 1469,
                            SourceUrl = "https://www.queenstownnz.co.nz/listing/queenstown-bay/605/"
                        },
                        new
                        {
                            Id = 15,
                            AvailabilityNote = "Open year round; track conditions can be muddy, icy or affected by storms.",
                            BestTime = "Dec - Feb",
                            BookingNote = "No booking; use the car park trailhead and carry weather-appropriate gear.",
                            Description = "An easy, picturesque walk through native bush to a secluded cove on Lake Wakatipu.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/bobs-cove-track.jpg",
                            Latitude = -45.068199999999997,
                            Longitude = 168.53980000000001,
                            Name = "Bobs Cove Track",
                            OpeningHoursNote = "Public walking track; check DOC conditions before visit.",
                            Rating = 4.9m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 682,
                            SourceUrl = "https://www.doc.govt.nz/parks-and-recreation/places-to-go/otago/places/queenstown-area/things-to-do/tracks/bobs-cove-track/"
                        },
                        new
                        {
                            Id = 16,
                            AvailabilityNote = "Open year round; spring and summer are especially colourful.",
                            BestTime = "Sep - Apr",
                            BookingNote = "No booking for gardens; weather and events may affect some areas.",
                            Description = "Historic riverside gardens beside Hagley Park.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/christchurch-botanic-gardens.jpg",
                            Latitude = -43.5306,
                            Longitude = 172.62620000000001,
                            Name = "Christchurch Botanic Gardens",
                            OpeningHoursNote = "Check Christchurch City Council’s current garden and visitor-centre hours before visit.",
                            Rating = 4.8m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 957,
                            SourceUrl = "https://ccc.govt.nz/parks-and-gardens/christchurch-botanic-gardens"
                        },
                        new
                        {
                            Id = 17,
                            AvailabilityNote = "Open year round; indoor attraction.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended in peak periods; allow time for timed experiences.",
                            Description = "Interactive Antarctic visitor experience beside Christchurch Airport.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/international-antarctic-centre.jpg",
                            Latitude = -43.486199999999997,
                            Longitude = 172.5488,
                            Name = "International Antarctic Centre",
                            OpeningHoursNote = "Check the International Antarctic Centre’s current daily hours before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 176,
                            SourceUrl = "https://www.iceberg.co.nz/"
                        },
                        new
                        {
                            Id = 18,
                            AvailabilityNote = "Open year round, subject to wind and weather.",
                            BestTime = "Year round",
                            BookingNote = "Book ahead in peak periods; gondola operations can be affected by high winds.",
                            Description = "Gondola ride with views over Lyttelton Harbour and the Canterbury Plains.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/christchurch-gondola.jpg",
                            Latitude = -43.582799999999999,
                            Longitude = 172.71190000000001,
                            Name = "Christchurch Gondola",
                            OpeningHoursNote = "Check Christchurch Gondola’s current operating hours before visit.",
                            Rating = 4.4m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 1075,
                            SourceUrl = "https://www.christchurchgondola.co.nz/"
                        },
                        new
                        {
                            Id = 19,
                            AvailabilityNote = "Open year round; indoor attraction.",
                            BestTime = "Year round",
                            BookingNote = "Booking recommended for groups; allow time for nearby central-city parking.",
                            Description = "Museum telling the story of the Canterbury earthquakes and recovery.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/quake-city.jpg",
                            Latitude = -43.528399999999998,
                            Longitude = 172.63220000000001,
                            Name = "Quake City",
                            OpeningHoursNote = "Check Quake City’s current hours before visit.",
                            Rating = 4.6m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 1438,
                            SourceUrl = "https://www.quakecity.co.nz/"
                        },
                        new
                        {
                            Id = 20,
                            AvailabilityNote = "Open year round; indoor/outdoor exhibits.",
                            BestTime = "Year round",
                            BookingNote = "General admission is usually free; book guided tours or special activities if required.",
                            Description = "Discover the history of New Zealand military aviation through engaging exhibits and historic aircraft.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/air-force-museum-of-new-zealand.jpg",
                            Latitude = -43.548299999999998,
                            Longitude = 172.54599999999999,
                            Name = "Air Force Museum of New Zealand",
                            OpeningHoursNote = "Check the museum’s current opening hours before visit.",
                            Rating = 4.3m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 630,
                            SourceUrl = "https://www.airforcemuseum.co.nz/"
                        },
                        new
                        {
                            Id = 21,
                            AvailabilityNote = "Open year round; outdoor animal experiences vary with weather and animal welfare needs.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended in school holidays; check encounter times and weather advice.",
                            Description = "New Zealand's only open-range zoo, offering unique up-close animal encounters.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/orana-wildlife-park.jpg",
                            Latitude = -43.468200000000003,
                            Longitude = 172.46360000000001,
                            Name = "Orana Wildlife Park",
                            OpeningHoursNote = "Check Orana’s current daily hours before visit.",
                            Rating = 4.2m,
                            RecommendedDuration = "5 hours",
                            ReviewCount = 314,
                            SourceUrl = "https://www.oranawildlifepark.co.nz/"
                        },
                        new
                        {
                            Id = 22,
                            AvailabilityNote = "Open year round; night tours and animal encounters may be seasonal.",
                            BestTime = "Year round",
                            BookingNote = "Book kiwi/night tours and encounters in advance.",
                            Description = "A wildlife park dedicated to New Zealand's native species and Māori cultural experiences.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/willowbank-wildlife-reserve.jpg",
                            Latitude = -43.467799999999997,
                            Longitude = 172.59370000000001,
                            Name = "Willowbank Wildlife Reserve",
                            OpeningHoursNote = "Check Willowbank’s current visitor hours before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 513,
                            SourceUrl = "https://www.willowbank.co.nz/"
                        },
                        new
                        {
                            Id = 23,
                            AvailabilityNote = "Year round; harbour cruises and wildlife trips are weather dependent.",
                            BestTime = "Sep - Apr",
                            BookingNote = "Book harbour cruises in advance; allow for the drive and possible weather cancellations.",
                            Description = "Banks Peninsula harbour town, suitable as a full-day excursion from Christchurch.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/akaroa-harbour-day-trip.jpg",
                            Latitude = -43.805799999999998,
                            Longitude = 172.9675,
                            Name = "Akaroa Harbour day trip",
                            OpeningHoursNote = "Check the chosen operator’s timetable before visit.",
                            Rating = 4.6m,
                            RecommendedDuration = "8 hours",
                            ReviewCount = 1144,
                            SourceUrl = "https://www.christchurchnz.com/explore/akaroa"
                        },
                        new
                        {
                            Id = 24,
                            AvailabilityNote = "Open year round; market and ferry activity varies by day.",
                            BestTime = "Year round",
                            BookingNote = "No booking for the waterfront; check parking and cruise-ship/event impacts.",
                            Description = "A historic port town set in a collapsed volcanic crater, featuring quirky shops and stunning views.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/lyttelton-harbour.jpg",
                            Latitude = -43.601500000000001,
                            Longitude = 172.72120000000001,
                            Name = "Lyttelton Harbour",
                            OpeningHoursNote = "Public harbour area; check individual businesses and event schedules.",
                            Rating = 4.9m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 519,
                            SourceUrl = "https://www.christchurchnz.com/explore/lyttelton"
                        },
                        new
                        {
                            Id = 25,
                            AvailabilityNote = "Open year round; best in settled conditions.",
                            BestTime = "Dec - Feb",
                            BookingNote = "No booking; check surf, tide and weather warnings before swimming or rock access.",
                            Description = "A popular coastal suburb known for its relaxed surf culture and iconic volcanic rock formations.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/sumner-beach-and-cave-rock.jpg",
                            Latitude = -43.567,
                            Longitude = 172.75839999999999,
                            Name = "Sumner Beach and Cave Rock",
                            OpeningHoursNote = "Public beach; no set hours.",
                            Rating = 4.4m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 1377,
                            SourceUrl = "https://ccc.govt.nz/parks-and-gardens/explore-parks/coastal-parks/sumner-beach"
                        },
                        new
                        {
                            Id = 26,
                            AvailabilityNote = "Operates seasonally and may be weather dependent.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended; rain, wind or river conditions may affect service.",
                            Description = "A tranquil and iconic Christchurch experience gliding along the Avon River in a flat-bottomed boat.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/punting-on-the-avon.jpg",
                            Latitude = -43.533200000000001,
                            Longitude = 172.6277,
                            Name = "Punting on the Avon",
                            OpeningHoursNote = "Check Punting on the Avon’s current departure times before visit.",
                            Rating = 4.6m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 497,
                            SourceUrl = "https://www.puntingontheavon.co.nz/"
                        },
                        new
                        {
                            Id = 27,
                            AvailabilityNote = "Open year round; trading hours vary by stall and day.",
                            BestTime = "Year round",
                            BookingNote = "No booking for market browsing; book restaurants separately if required.",
                            Description = "A bustling indoor market offering diverse street food, fresh local produce, and boutique stalls.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/riverside-market.jpg",
                            Latitude = -43.532299999999999,
                            Longitude = 172.63239999999999,
                            Name = "Riverside Market",
                            OpeningHoursNote = "Check Riverside Market’s current opening hours before visit.",
                            Rating = 4.6m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 890,
                            SourceUrl = "https://riverside.nz/"
                        },
                        new
                        {
                            Id = 28,
                            AvailabilityNote = "Open year round; exposed tracks are best in dry, low-wind conditions.",
                            BestTime = "Year round",
                            BookingNote = "No booking; carry water, sun protection and layers; avoid exposed routes in severe weather.",
                            Description = "A rugged volcanic range offering extensive walking and biking trails with panoramic city and harbour views.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/port-hills.jpg",
                            Latitude = -43.633800000000001,
                            Longitude = 172.6223,
                            Name = "Port Hills",
                            OpeningHoursNote = "Public tracks; check Christchurch City Council and weather/fire restrictions before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "4 hours",
                            ReviewCount = 949,
                            SourceUrl = "https://ccc.govt.nz/parks-and-gardens/explore-parks/port-hills"
                        },
                        new
                        {
                            Id = 29,
                            AvailabilityNote = "Confirm reopening and temporary exhibition arrangements before planning.",
                            BestTime = "Year round",
                            BookingNote = "No booking assumption; verify venue location, ticketing and opening information first.",
                            Description = "A cultural heritage museum showcasing the rich natural and human history of the Canterbury region.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/canterbury-museum.jpg",
                            Latitude = -43.531199999999998,
                            Longitude = 172.6268,
                            Name = "Canterbury Museum",
                            OpeningHoursNote = "Check the Canterbury Museum website before visit; redevelopment may affect access.",
                            Rating = 4.5m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 305,
                            SourceUrl = "https://canterburymuseum.com/"
                        },
                        new
                        {
                            Id = 30,
                            AvailabilityNote = "Open year round; galleries, shops and events have separate schedules.",
                            BestTime = "Year round",
                            BookingNote = "No booking to explore public areas; book performances, tours or workshops separately.",
                            Description = "A vibrant hub for arts, culture, and education set within stunning restored Gothic Revival buildings.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/the-arts-centre.jpg",
                            Latitude = -43.531300000000002,
                            Longitude = 172.6284,
                            Name = "The Arts Centre",
                            OpeningHoursNote = "Check The Arts Centre’s current building and venue hours before visit.",
                            Rating = 4.7m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 744,
                            SourceUrl = "https://artscentre.org.nz/"
                        },
                        new
                        {
                            Id = 31,
                            AvailabilityNote = "Open year round; outdoor SkyWalk/SkyJump is weather dependent.",
                            BestTime = "Year round",
                            BookingNote = "Pre-book SkyWalk/SkyJump and peak observation visits; outdoor activities can be weather cancelled.",
                            Description = "Observation tower with panoramic views across Auckland and the Hauraki Gulf.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/sky-tower.jpg",
                            Latitude = -36.848500000000001,
                            Longitude = 174.76220000000001,
                            Name = "Sky Tower",
                            OpeningHoursNote = "Check SkyCity’s current attraction hours before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 535,
                            SourceUrl = "https://skycityauckland.co.nz/sky-tower/"
                        },
                        new
                        {
                            Id = 32,
                            AvailabilityNote = "Open year round; indoor museum and outdoor Domain.",
                            BestTime = "Year round",
                            BookingNote = "Book paid exhibitions or events in advance; allow time for parking or public transport.",
                            Description = "Museum of natural history and Aotearoa New Zealand stories in the Domain.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/auckland-museum.jpg",
                            Latitude = -36.860599999999998,
                            Longitude = 174.77780000000001,
                            Name = "Auckland Museum",
                            OpeningHoursNote = "Check Auckland Museum’s current opening hours before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 1112,
                            SourceUrl = "https://www.aucklandmuseum.com/"
                        },
                        new
                        {
                            Id = 33,
                            AvailabilityNote = "Open year round; outdoor areas and encounters are weather dependent.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended in peak periods; check animal encounter requirements.",
                            Description = "Conservation-focused zoo in Western Springs.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/auckland-zoo.jpg",
                            Latitude = -36.863100000000003,
                            Longitude = 174.7176,
                            Name = "Auckland Zoo",
                            OpeningHoursNote = "Check Auckland Zoo’s current daily hours before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "4 hours",
                            ReviewCount = 981,
                            SourceUrl = "https://www.aucklandzoo.co.nz/"
                        },
                        new
                        {
                            Id = 34,
                            AvailabilityNote = "Open year round; ferry sailings and outdoor activities depend on weather.",
                            BestTime = "Nov - Mar",
                            BookingNote = "Book ferries, tours and popular wineries in advance; allow for weather or sea-condition disruptions.",
                            Description = "Hauraki Gulf island for beaches, art and vineyard visits; allow a full day.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/waiheke-island-day-trip.jpg",
                            Latitude = -36.843000000000004,
                            Longitude = 174.767,
                            Name = "Waiheke Island day trip",
                            OpeningHoursNote = "Check Fullers360 ferry timetable and chosen winery/attraction hours before visit.",
                            Rating = 4.2m,
                            RecommendedDuration = "8 hours",
                            ReviewCount = 757,
                            SourceUrl = "https://www.fullers.co.nz/destinations-and-experiences/waiheke-island/"
                        },
                        new
                        {
                            Id = 35,
                            AvailabilityNote = "Open year round; ferry service and summit track conditions are weather dependent.",
                            BestTime = "Nov - Mar",
                            BookingNote = "Pre-book ferry; take food, water and sun protection—there are no shops on Rangitoto.",
                            Description = "Volcanic island day trip with a summit walk and harbour views.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/rangitoto-island-day-trip.jpg",
                            Latitude = -36.843000000000004,
                            Longitude = 174.767,
                            Name = "Rangitoto Island day trip",
                            OpeningHoursNote = "Check Fullers360 timetable and DOC island advice before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "7 hours",
                            ReviewCount = 1154,
                            SourceUrl = "https://www.aucklandnz.com/explore/rangitoto-island"
                        },
                        new
                        {
                            Id = 36,
                            AvailabilityNote = "Open year round; indoor attraction.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended in weekends and school holidays.",
                            Description = "An iconic underwater attraction featuring penguin colonies, shark tunnels, and marine rescue exhibits.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/sea-life-kelly-tarltons-aquarium.jpg",
                            Latitude = -36.847499999999997,
                            Longitude = 174.81829999999999,
                            Name = "SEA LIFE Kelly Tarlton’s Aquarium",
                            OpeningHoursNote = "Check SEA LIFE Kelly Tarlton’s current hours before visit.",
                            Rating = 4.3m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 425,
                            SourceUrl = "https://www.visitsealife.com/auckland/"
                        },
                        new
                        {
                            Id = 37,
                            AvailabilityNote = "Open year round; indoor/outdoor exhibits.",
                            BestTime = "Year round",
                            BookingNote = "Book special events and school-holiday activities in advance where offered.",
                            Description = "An interactive museum exploring the history and future of New Zealand's transport and technology.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/museum-of-transport-and-technology.jpg",
                            Latitude = -36.866500000000002,
                            Longitude = 174.71789999999999,
                            Name = "Museum of Transport and Technology",
                            OpeningHoursNote = "Check MOTAT’s current opening hours before visit.",
                            Rating = 4.6m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 1277,
                            SourceUrl = "https://www.motat.nz/"
                        },
                        new
                        {
                            Id = 38,
                            AvailabilityNote = "Open year round; harbour sailing experiences are weather dependent.",
                            BestTime = "Year round",
                            BookingNote = "Book heritage sailings in advance; sailings can be weather affected.",
                            Description = "Discover the stories of the people and ships that shaped New Zealand's seafaring history.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/new-zealand-maritime-museum.jpg",
                            Latitude = -36.841900000000003,
                            Longitude = 174.76339999999999,
                            Name = "New Zealand Maritime Museum",
                            OpeningHoursNote = "Check the Maritime Museum’s current hours before visit.",
                            Rating = 4.8m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 1357,
                            SourceUrl = "https://www.maritimemuseum.co.nz/"
                        },
                        new
                        {
                            Id = 39,
                            AvailabilityNote = "Open year round; gallery programme and special exhibitions vary.",
                            BestTime = "Year round",
                            BookingNote = "Book ticketed exhibitions or events in advance when required.",
                            Description = "New Zealand's largest visual arts institution, housing an extensive collection of national and international art.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/auckland-art-gallery-toi-o-tamaki.jpg",
                            Latitude = -36.850200000000001,
                            Longitude = 174.76609999999999,
                            Name = "Auckland Art Gallery Toi o Tāmaki",
                            OpeningHoursNote = "Check Auckland Art Gallery’s current opening hours before visit.",
                            Rating = 4.4m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 989,
                            SourceUrl = "https://www.aucklandartgallery.com/"
                        },
                        new
                        {
                            Id = 40,
                            AvailabilityNote = "Open year round; exposed summit is best in settled weather.",
                            BestTime = "Year round",
                            BookingNote = "No booking; use daylight hours and allow for a walk from parking.",
                            Description = "A significant volcanic peak and historic park offering 360-degree views of Auckland.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/maungakiekie-one-tree-hill.jpg",
                            Latitude = -36.896700000000003,
                            Longitude = 174.7765,
                            Name = "Maungakiekie / One Tree Hill",
                            OpeningHoursNote = "Public park; check Cornwall Park and local weather information before visit.",
                            Rating = 4.3m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 1426,
                            SourceUrl = "https://cornwallpark.co.nz/"
                        },
                        new
                        {
                            Id = 41,
                            AvailabilityNote = "Open year round; ferry and outdoor walk conditions are weather dependent.",
                            BestTime = "Year round",
                            BookingNote = "No booking for North Head; ferry services can be weather affected and tunnels may have access limits.",
                            Description = "A charming historic village paired with a coastal reserve known for its military tunnels and harbour views.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/devonport-waterfront-and-north-head.jpg",
                            Latitude = -36.832900000000002,
                            Longitude = 174.7961,
                            Name = "Devonport waterfront and North Head",
                            OpeningHoursNote = "Check Fullers360 timetable and DOC North Head information before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "4 hours",
                            ReviewCount = 1480,
                            SourceUrl = "https://www.doc.govt.nz/parks-and-recreation/places-to-go/auckland/places/north-head-historic-reserve/"
                        },
                        new
                        {
                            Id = 42,
                            AvailabilityNote = "Open year round; scheduled ferry access and outdoor walking are weather dependent.",
                            BestTime = "Year round",
                            BookingNote = "Book ferry well ahead; take food, water and walking gear—check weather cancellations.",
                            Description = "A renowned open sanctuary for native birdlife and conservation, accessible by a scenic ferry ride.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/tiritiri-matangi-island-day-trip.jpg",
                            Latitude = -36.843000000000004,
                            Longitude = 174.767,
                            Name = "Tiritiri Matangi Island day trip",
                            OpeningHoursNote = "Check Explore Group ferry timetable and DOC visitor information before visit.",
                            Rating = 4.6m,
                            RecommendedDuration = "8 hours",
                            ReviewCount = 248,
                            SourceUrl = "https://www.doc.govt.nz/parks-and-recreation/places-to-go/auckland/places/tiritiri-matangi-open-sanctuary/"
                        },
                        new
                        {
                            Id = 43,
                            AvailabilityNote = "Open year round; best in settled weather and daylight.",
                            BestTime = "Year round",
                            BookingNote = "No booking; check swim, weather and traffic conditions before visit.",
                            Description = "A picturesque coastal route leading to a vibrant seaside suburb with a beautiful sandy beach and eateries.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/mission-bay-and-tamaki-drive.jpg",
                            Latitude = -36.847999999999999,
                            Longitude = 174.83150000000001,
                            Name = "Mission Bay and Tāmaki Drive",
                            OpeningHoursNote = "Public waterfront; no set hours.",
                            Rating = 4.7m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 441,
                            SourceUrl = "https://www.aucklandnz.com/explore/mission-bay"
                        },
                        new
                        {
                            Id = 44,
                            AvailabilityNote = "Open year round; events may limit vehicle access or parking.",
                            BestTime = "Sep - Apr",
                            BookingNote = "No booking; use daylight hours and combine with Auckland Museum if suitable.",
                            Description = "Auckland's oldest park, featuring expansive green spaces, walking tracks, and the historic Wintergardens.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/auckland-domain.jpg",
                            Latitude = -36.8596,
                            Longitude = 174.7758,
                            Name = "Auckland Domain",
                            OpeningHoursNote = "Public park; check Auckland Council information for event impacts.",
                            Rating = 4.5m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 437,
                            SourceUrl = "https://www.aucklandcouncil.govt.nz/parks-recreation/get-outdoors/find-a-park/Pages/park-details.aspx?parkID=1"
                        },
                        new
                        {
                            Id = 45,
                            AvailabilityNote = "Open year round; indoor attraction.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended; arrive before your timed session.",
                            Description = "An immersive and wildly imaginative experience exploring the worlds of horror, sci-fi, and fantasy film-making.",
                            DestinationId = 3,
                            ImageUrl = "assets/images/weta-workshop-unleashed.jpg",
                            Latitude = -36.8489,
                            Longitude = 174.7621,
                            Name = "Wētā Workshop Unleashed",
                            OpeningHoursNote = "Check Wētā Workshop Unleashed’s current session times before visit.",
                            Rating = 4.6m,
                            RecommendedDuration = "2 hours",
                            ReviewCount = 1343,
                            SourceUrl = "https://tours.wetaworkshop.com/auckland/"
                        },
                        new
                        {
                            Id = 46,
                            AvailabilityNote = "Open year round; daily boat departures across Lake Te Anau.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended; check-in 30 minutes prior to departure; requires bending/walking in caves.",
                            Description = "A magical underground experience starting with a scenic lake cruise to a hidden limestone cave illuminated by thousands of glowworms.",
                            DestinationId = 8,
                            ImageUrl = "assets/images/te-anau-glowworm-caves.jpg",
                            Latitude = -45.416499999999999,
                            Longitude = 167.71180000000001,
                            Name = "Te Anau Glowworm Caves",
                            OpeningHoursNote = "Open 7 days, daily departures. Check official website before visit.",
                            Rating = 4.5m,
                            RecommendedDuration = "2.25 hours",
                            ReviewCount = 850,
                            SourceUrl = "https://www.realnz.com/en/experiences/glowworm-caves/te-anau-glowworm-caves/"
                        },
                        new
                        {
                            Id = 47,
                            AvailabilityNote = "Great Walks season runs late October to April; day walks accessible year round in good weather.",
                            BestTime = "Sep - Apr",
                            BookingNote = "No booking required for day walks; check DOC weather and track alerts before setting out.",
                            Description = "An accessible section of the famous Kepler Great Walk, leading through ancient beech forests along the lake shore.",
                            DestinationId = 8,
                            ImageUrl = "assets/images/kepler-track-day-walk.jpg",
                            Latitude = -45.439799999999998,
                            Longitude = 167.68299999999999,
                            Name = "Kepler Track Day Walk",
                            OpeningHoursNote = "Public walking track; accessible during daylight hours.",
                            Rating = 4.8m,
                            RecommendedDuration = "3 hours",
                            ReviewCount = 620,
                            SourceUrl = "https://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/kepler-track/"
                        },
                        new
                        {
                            Id = 48,
                            AvailabilityNote = "Operates year round; full-day excursion departing from Manapouri.",
                            BestTime = "Nov - Mar",
                            BookingNote = "Advance booking essential; departures leave from Pearl Harbour in Manapouri.",
                            Description = "A tranquil and remote wilderness cruise through a deep, pristine fiord known for its serene waters and native wildlife.",
                            DestinationId = 8,
                            ImageUrl = "assets/images/doubtful-sound-wilderness-cruise.jpg",
                            Latitude = -45.563600000000001,
                            Longitude = 167.6163,
                            Name = "Doubtful Sound Wilderness Cruise",
                            OpeningHoursNote = "Check official website before visit for seasonal departure times.",
                            Rating = 4.7m,
                            RecommendedDuration = "7 hours",
                            ReviewCount = 540,
                            SourceUrl = "https://www.realnz.com/en/experiences/cruises/doubtful-sound-wilderness-cruises/"
                        },
                        new
                        {
                            Id = 49,
                            AvailabilityNote = "Open year round from dawn to dusk.",
                            BestTime = "Year round",
                            BookingNote = "Free entry (gold coin donation appreciated); guided tour feeds can be booked.",
                            Description = "A lakeside conservation haven providing a rare chance to see endangered native birds like the Takahē up close.",
                            DestinationId = 8,
                            ImageUrl = "assets/images/te-anau-bird-sanctuary.jpg",
                            Latitude = -45.426200000000001,
                            Longitude = 167.70509999999999,
                            Name = "Te Anau Bird Sanctuary",
                            OpeningHoursNote = "Open daily from dawn to dusk.",
                            Rating = 4.6m,
                            RecommendedDuration = "1 hours",
                            ReviewCount = 310,
                            SourceUrl = "https://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/te-anau-bird-sanctuary/"
                        },
                        new
                        {
                            Id = 50,
                            AvailabilityNote = "Open year round; an excellent indoor activity.",
                            BestTime = "Year round",
                            BookingNote = "Advance booking recommended for popular evening screenings.",
                            Description = "A boutique cinema showcasing the custom-shot documentary 'Ata Whenua - Shadowland', capturing Fiordland's wild landscapes.",
                            DestinationId = 8,
                            ImageUrl = "assets/images/fiordland-cinema.jpg",
                            Latitude = -45.414999999999999,
                            Longitude = 167.71350000000001,
                            Name = "Fiordland Cinema",
                            OpeningHoursNote = "Check official website for current screening showtimes.",
                            Rating = 4.8m,
                            RecommendedDuration = "1 hours",
                            ReviewCount = 420,
                            SourceUrl = "https://www.fiordlandcinema.co.nz/"
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.AttractionCategory", b =>
                {
                    b.Property<int>("AttractionId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("AttractionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("AttractionCategories");

                    b.HasData(
                        new
                        {
                            AttractionId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            AttractionId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            AttractionId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            AttractionId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            AttractionId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            AttractionId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            AttractionId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            AttractionId = 7,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sightseeing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Culture"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Food & Wine"
                        },
                        new
                        {
                            Id = 6,
                            Name = "City"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Relaxation"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wildlife"
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "New Zealand's adventure capital, surrounded by mountains and Lake Wakatipu.",
                            ImageUrl = "assets/images/queenstown.png",
                            IsPopular = true,
                            Name = "Queenstown",
                            Rating = 4.9m,
                            RegionId = 15,
                            ReviewCount = 980
                        },
                        new
                        {
                            Id = 2,
                            Description = "A geothermal wonderland known for Māori culture, hot springs and outdoor adventures.",
                            ImageUrl = "assets/images/rotorua.jpg",
                            IsPopular = true,
                            Name = "Rotorua",
                            Rating = 4.8m,
                            RegionId = 4,
                            ReviewCount = 980
                        },
                        new
                        {
                            Id = 3,
                            Description = "New Zealand's largest city, surrounded by beautiful harbours, islands and beaches.",
                            ImageUrl = "assets/images/auckland.jpg",
                            IsPopular = true,
                            Name = "Auckland",
                            Rating = 4.7m,
                            RegionId = 2,
                            ReviewCount = 1200
                        },
                        new
                        {
                            Id = 4,
                            Description = "A relaxed lakeside town surrounded by mountains and outdoor adventures.",
                            ImageUrl = "assets/images/wanaka.jpg",
                            IsPopular = true,
                            Name = "Wanaka",
                            Rating = 4.8m,
                            RegionId = 15,
                            ReviewCount = 850
                        },
                        new
                        {
                            Id = 5,
                            Description = "New Zealand's creative capital, known for culture, food and waterfront views.",
                            ImageUrl = "assets/images/wellington.jpg",
                            IsPopular = true,
                            Name = "Wellington",
                            Rating = 4.7m,
                            RegionId = 9,
                            ReviewCount = 920
                        },
                        new
                        {
                            Id = 6,
                            Description = "A vibrant South Island city surrounded by mountains, gardens and natural landscapes.",
                            ImageUrl = "assets/images/christchurch.jpg",
                            IsPopular = true,
                            Name = "Christchurch",
                            Rating = 4.7m,
                            RegionId = 14,
                            ReviewCount = 760
                        },
                        new
                        {
                            Id = 7,
                            Description = "A charming Waikato town and gateway to the famous Hobbiton Movie Set.",
                            ImageUrl = "assets/images/matamata.jpg",
                            IsPopular = false,
                            Name = "Matamata",
                            Rating = 4.7m,
                            RegionId = 3,
                            ReviewCount = 600
                        },
                        new
                        {
                            Id = 8,
                            Description = "A scenic lakeside town and gateway to Fiordland National Park and Milford Sound.",
                            ImageUrl = "assets/images/te-anau.jpg",
                            IsPopular = true,
                            Name = "Te Anau",
                            Rating = 4.8m,
                            RegionId = 16,
                            ReviewCount = 720
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.DestinationCategory", b =>
                {
                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("DestinationId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DestinationCategories");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            DestinationId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            DestinationId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            DestinationId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            DestinationId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            DestinationId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            DestinationId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            DestinationId = 3,
                            CategoryId = 6
                        },
                        new
                        {
                            DestinationId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            DestinationId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            DestinationId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            DestinationId = 5,
                            CategoryId = 6
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Island", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Islands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Aotearoa's North Island, known for culture, beaches, geothermal landscapes and vibrant cities.",
                            ImageUrl = "assets/images/north-island.jpg",
                            Name = "North Island"
                        },
                        new
                        {
                            Id = 2,
                            Description = "New Zealand's South Island, famous for mountains, lakes, fiords and outdoor adventures.",
                            ImageUrl = "assets/images/south-island.jpg",
                            Name = "South Island"
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IslandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IslandId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            IslandId = 1,
                            Name = "Northland"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            IslandId = 1,
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IslandId = 1,
                            Name = "Waikato"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            IslandId = 1,
                            Name = "Bay of Plenty"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            IslandId = 1,
                            Name = "Gisborne"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            IslandId = 1,
                            Name = "Taranaki"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            IslandId = 1,
                            Name = "Manawatū-Whanganui"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            IslandId = 1,
                            Name = "Hawke's Bay"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            IslandId = 1,
                            Name = "Wellington"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            IslandId = 2,
                            Name = "Tasman"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            IslandId = 2,
                            Name = "Nelson"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            IslandId = 2,
                            Name = "Marlborough"
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            IslandId = 2,
                            Name = "West Coast"
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            IslandId = 2,
                            Name = "Canterbury"
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            IslandId = 2,
                            Name = "Otago"
                        },
                        new
                        {
                            Id = 16,
                            Description = "",
                            IslandId = 2,
                            Name = "Southland"
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BudgetRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TripStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "StartDate");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.TripDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "DayNumber")
                        .IsUnique();

                    b.ToTable("TripDays");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.TripStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttractionId")
                        .HasColumnType("int");

                    b.Property<string>("CustomName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PlannedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TripDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.HasIndex("TripDayId");

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Attraction", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Destination", "Destination")
                        .WithMany("Attractions")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.AttractionCategory", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Attraction", "Attraction")
                        .WithMany("AttractionCategories")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WanderKiwi.Domain.Entities.Category", "Category")
                        .WithMany("AttractionCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Destination", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Region", "Region")
                        .WithMany("Destinations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.DestinationCategory", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WanderKiwi.Domain.Entities.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Region", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Island", "Island")
                        .WithMany("Regions")
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Island");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.TripDay", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Trip", "Trip")
                        .WithMany("Days")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.TripStop", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WanderKiwi.Domain.Entities.TripDay", "TripDay")
                        .WithMany("Stops")
                        .HasForeignKey("TripDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("TripDay");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Attraction", b =>
                {
                    b.Navigation("AttractionCategories");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Category", b =>
                {
                    b.Navigation("AttractionCategories");

                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Island", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Region", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.TripDay", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
