// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WanderKiwi.Infrastructure.Data;

#nullable disable

namespace WanderKiwi.Infrastructure.Migrations
{
    [DbContext(typeof(WanderKiwiDbContext))]
    [Migration("20260821093500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecommendedDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestTime = "Dec - Feb",
                            Description = "Take in breathtaking views of Queenstown, Lake Wakatipu and the surrounding mountains.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/skyline-queenstown.jpg",
                            Latitude = -45.031199999999998,
                            Longitude = 168.6626,
                            Name = "Skyline Queenstown",
                            Rating = 4.8m,
                            RecommendedDuration = "2-3 hours",
                            ReviewCount = 1200
                        },
                        new
                        {
                            Id = 2,
                            BestTime = "Dec - Apr",
                            Description = "A challenging alpine hike offering spectacular views over Queenstown and Lake Wakatipu.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/ben-lomond.jpg",
                            Latitude = -45.009700000000002,
                            Longitude = 168.61670000000001,
                            Name = "Ben Lomond Track",
                            Rating = 4.7m,
                            RecommendedDuration = "6-8 hours",
                            ReviewCount = 713
                        },
                        new
                        {
                            Id = 3,
                            BestTime = "Dec - Feb",
                            Description = "Enjoy a classic cruise across Lake Wakatipu aboard a historic steamship.",
                            DestinationId = 1,
                            ImageUrl = "assets/images/tss-earnslaw.jpg",
                            Latitude = -45.030999999999999,
                            Longitude = 168.66,
                            Name = "TSS Earnslaw Cruise",
                            Rating = 4.7m,
                            RecommendedDuration = "1.5-2 hours",
                            ReviewCount = 980
                        },
                        new
                        {
                            Id = 4,
                            BestTime = "Dec - Feb",
                            Description = "A spectacular fiord surrounded by towering peaks, waterfalls and native rainforest.",
                            DestinationId = 8,
                            ImageUrl = "assets/images/milford.jpg",
                            Latitude = -44.641399999999997,
                            Longitude = 167.9254,
                            Name = "Milford Sound",
                            Rating = 4.9m,
                            RecommendedDuration = "4-6 hours",
                            ReviewCount = 1420
                        },
                        new
                        {
                            Id = 5,
                            BestTime = "Dec - Feb",
                            Description = "Step into the lush pastures of the Shire from The Lord of the Rings film trilogy.",
                            DestinationId = 7,
                            ImageUrl = "assets/images/hobbiton.jpg",
                            Latitude = -37.872100000000003,
                            Longitude = 175.68260000000001,
                            Name = "Hobbiton Movie Set",
                            Rating = 4.8m,
                            RecommendedDuration = "2-3 hours",
                            ReviewCount = 1250
                        },
                        new
                        {
                            Id = 6,
                            BestTime = "Nov - Mar",
                            Description = "Explore colourful geothermal pools, volcanic landscapes and geothermal activity.",
                            DestinationId = 2,
                            ImageUrl = "assets/images/waiotapu.jpg",
                            Latitude = -38.357399999999998,
                            Longitude = 176.36680000000001,
                            Name = "Wai-O-Tapu Thermal Wonderland",
                            Rating = 4.7m,
                            RecommendedDuration = "2-3 hours",
                            ReviewCount = 1100
                        },
                        new
                        {
                            Id = 7,
                            BestTime = "Sep - Apr",
                            Description = "New Zealand's highest mountain surrounded by spectacular alpine landscapes and glaciers.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/mountcook.jpg",
                            Latitude = -43.734400000000001,
                            Longitude = 170.14109999999999,
                            Name = "Aoraki / Mount Cook",
                            Rating = 4.9m,
                            RecommendedDuration = "1-2 days",
                            ReviewCount = 1500
                        },
                        new
                        {
                            Id = 8,
                            BestTime = "Dec - Mar",
                            Description = "A stunning coastal national park known for golden beaches, clear water and walking trails.",
                            DestinationId = 6,
                            ImageUrl = "assets/images/abel-tasman.jpg",
                            Latitude = -40.900599999999997,
                            Longitude = 173.07689999999999,
                            Name = "Abel Tasman National Park",
                            Rating = 4.8m,
                            RecommendedDuration = "1-2 days",
                            ReviewCount = 900
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.AttractionCategory", b =>
                {
                    b.Property<int>("AttractionId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("AttractionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("AttractionCategories");

                    b.HasData(
                        new
                        {
                            AttractionId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            AttractionId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            AttractionId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            AttractionId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            AttractionId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            AttractionId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            AttractionId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            AttractionId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            AttractionId = 7,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sightseeing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Culture"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Food & Wine"
                        },
                        new
                        {
                            Id = 6,
                            Name = "City"
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "New Zealand's adventure capital, surrounded by mountains and Lake Wakatipu.",
                            ImageUrl = "assets/images/queenstown.png",
                            IsPopular = true,
                            Name = "Queenstown",
                            Rating = 4.9m,
                            RegionId = 15,
                            ReviewCount = 980
                        },
                        new
                        {
                            Id = 2,
                            Description = "A geothermal wonderland known for Māori culture, hot springs and outdoor adventures.",
                            ImageUrl = "assets/images/rotorua.jpg",
                            IsPopular = true,
                            Name = "Rotorua",
                            Rating = 4.8m,
                            RegionId = 4,
                            ReviewCount = 980
                        },
                        new
                        {
                            Id = 3,
                            Description = "New Zealand's largest city, surrounded by beautiful harbours, islands and beaches.",
                            ImageUrl = "assets/images/auckland.jpg",
                            IsPopular = true,
                            Name = "Auckland",
                            Rating = 4.7m,
                            RegionId = 2,
                            ReviewCount = 1200
                        },
                        new
                        {
                            Id = 4,
                            Description = "A relaxed lakeside town surrounded by mountains and outdoor adventures.",
                            ImageUrl = "assets/images/wanaka.jpg",
                            IsPopular = true,
                            Name = "Wanaka",
                            Rating = 4.8m,
                            RegionId = 15,
                            ReviewCount = 850
                        },
                        new
                        {
                            Id = 5,
                            Description = "New Zealand's creative capital, known for culture, food and waterfront views.",
                            ImageUrl = "assets/images/wellington.jpg",
                            IsPopular = true,
                            Name = "Wellington",
                            Rating = 4.7m,
                            RegionId = 9,
                            ReviewCount = 920
                        },
                        new
                        {
                            Id = 6,
                            Description = "A vibrant South Island city surrounded by mountains, gardens and natural landscapes.",
                            ImageUrl = "assets/images/christchurch.jpg",
                            IsPopular = true,
                            Name = "Christchurch",
                            Rating = 4.7m,
                            RegionId = 14,
                            ReviewCount = 760
                        },
                        new
                        {
                            Id = 7,
                            Description = "A charming Waikato town and gateway to the famous Hobbiton Movie Set.",
                            ImageUrl = "assets/images/matamata.jpg",
                            IsPopular = false,
                            Name = "Matamata",
                            Rating = 4.7m,
                            RegionId = 3,
                            ReviewCount = 600
                        },
                        new
                        {
                            Id = 8,
                            Description = "A scenic lakeside town and gateway to Fiordland National Park and Milford Sound.",
                            ImageUrl = "assets/images/te-anau.jpg",
                            IsPopular = true,
                            Name = "Te Anau",
                            Rating = 4.8m,
                            RegionId = 16,
                            ReviewCount = 720
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.DestinationCategory", b =>
                {
                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("DestinationId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DestinationCategories");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            DestinationId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            DestinationId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            DestinationId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            DestinationId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            DestinationId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            DestinationId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            DestinationId = 3,
                            CategoryId = 6
                        },
                        new
                        {
                            DestinationId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            DestinationId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            DestinationId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            DestinationId = 5,
                            CategoryId = 6
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Island", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Islands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Aotearoa's North Island, known for culture, beaches, geothermal landscapes and vibrant cities.",
                            ImageUrl = "assets/images/north-island.jpg",
                            Name = "North Island"
                        },
                        new
                        {
                            Id = 2,
                            Description = "New Zealand's South Island, famous for mountains, lakes, fiords and outdoor adventures.",
                            ImageUrl = "assets/images/south-island.jpg",
                            Name = "South Island"
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IslandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IslandId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            IslandId = 1,
                            Name = "Northland"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            IslandId = 1,
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IslandId = 1,
                            Name = "Waikato"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            IslandId = 1,
                            Name = "Bay of Plenty"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            IslandId = 1,
                            Name = "Gisborne"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            IslandId = 1,
                            Name = "Taranaki"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            IslandId = 1,
                            Name = "Manawatū-Whanganui"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            IslandId = 1,
                            Name = "Hawke's Bay"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            IslandId = 1,
                            Name = "Wellington"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            IslandId = 2,
                            Name = "Tasman"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            IslandId = 2,
                            Name = "Nelson"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            IslandId = 2,
                            Name = "Marlborough"
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            IslandId = 2,
                            Name = "West Coast"
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            IslandId = 2,
                            Name = "Canterbury"
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            IslandId = 2,
                            Name = "Otago"
                        },
                        new
                        {
                            Id = 16,
                            Description = "",
                            IslandId = 2,
                            Name = "Southland"
                        });
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Attraction", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Destination", "Destination")
                        .WithMany("Attractions")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.AttractionCategory", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Attraction", "Attraction")
                        .WithMany("AttractionCategories")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WanderKiwi.Domain.Entities.Category", "Category")
                        .WithMany("AttractionCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Destination", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Region", "Region")
                        .WithMany("Destinations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.DestinationCategory", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WanderKiwi.Domain.Entities.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Region", b =>
                {
                    b.HasOne("WanderKiwi.Domain.Entities.Island", "Island")
                        .WithMany("Regions")
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Island");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Attraction", b =>
                {
                    b.Navigation("AttractionCategories");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Category", b =>
                {
                    b.Navigation("AttractionCategories");

                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Island", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("WanderKiwi.Domain.Entities.Region", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
